export const LOGIN_USER = "LOGIN_USER"
export const SIGNUP_USER = "SIGNUP_USER"
export const SET_TOKEN = "SET_TOKEN"
export const SET_AUTHENTICATION = "SET_AUTHENTICATION"
export const SET_USER = "SET_USER"